In [1]:
import pandas as pd

produccion = pd.DataFrame({
    "codigo_municipio": [15001, 15238, 15516],
    "cultivo": ["Papa", "Cebolla", "Arveja"],
    "toneladas": [1200, 850, 430],
})

display(produccion)

   codigo_municipio  cultivo  toneladas
0             15001     Papa       1200
1             15238  Cebolla        850
2             15516   Arveja        430

In [2]:
municipios = pd.DataFrame({
    "codigo_municipio": [15001, 15238, 15759],
    "nombre_municipio": ["Tunja", "Duitama", "Sogamoso"],
})

display(municipios)

   codigo_municipio nombre_municipio
0             15001            Tunja
1             15238          Duitama
2             15759         Sogamoso

In [3]:
inner = pd.merge(produccion, municipios, on="codigo_municipio", how="inner")

display(inner)

   codigo_municipio  cultivo  toneladas nombre_municipio
0             15001     Papa       1200            Tunja
1             15238  Cebolla        850          Duitama

In [4]:
left = pd.merge(produccion, municipios, on="codigo_municipio", how="left")

display(left)

   codigo_municipio  cultivo  toneladas nombre_municipio
0             15001     Papa       1200            Tunja
1             15238  Cebolla        850          Duitama
2             15516   Arveja        430              NaN

In [5]:
right = pd.merge(produccion, municipios, on="codigo_municipio", how="right")

display(right)

   codigo_municipio  cultivo  toneladas nombre_municipio
0             15001     Papa     1200.0            Tunja
1             15238  Cebolla      850.0          Duitama
2             15759      NaN        NaN         Sogamoso